# Generated by Django 3.0.7 on 2020-07-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('std', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
