# Generated by Django 3.0.7 on 2020-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200702_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='s_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='t_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
